#!/usr/bin/env python3
"""Runnable check for sync_depot_keys.py's key extraction.

    ./tools/depot_keys_test.py

Imports the real KEY_RE rather than restating it, so this fails when that
pattern changes without the cases being thought about again.

Worth having because getting this wrong is invisible from every side. A key the
pattern misses is not an error: collect_keys simply does not see it, the script
prints "nothing to do", config.vdf keeps whatever it already had, and the only
symptom is a download that finishes and then reports the content as still
encrypted, days later, with nothing anywhere connecting the two.

That is not hypothetical. Requiring a flag of 1 dropped 291 keys on the machine
where it was found, across most of a library, and the sync reported success
every time.
"""
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("sdk", HERE / "sync_depot_keys.py")
sdk = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sdk)

KEY = "a" * 64
failures = 0


def check(ok, what):
    global failures
    print(f"  {'ok  ' if ok else 'FAIL'} {what}")
    if not ok:
        failures += 1


def found(text):
    return dict(sdk.KEY_RE.findall(text))


print("The flag in the middle, which the module never reads")
# lua_addappid takes the id from argument one and the key from argument three.
# Argument two is not consulted, so every one of these is the same manifest as
# far as the thing consuming it is concerned.
for flag in ("0", "1", "2"):
    got = found(f'addappid(123,{flag},"{KEY}")')
    check(got.get("123") == KEY, f"a flag of {flag} still yields the key")

print("Spacing, because manifests are generated by several different tools")
for text, why in (
    (f'addappid( 123 , 1 , "{KEY}" )', "spaces around every argument"),
    (f'\taddappid(123,0,"{KEY}")', "a leading tab"),
    (f'  addappid(123,0,"{KEY}")', "leading spaces"),
):
    check(found(text).get("123") == KEY, why)

print("What must not be read as a key")
for text, why in (
    ("addappid(123)", "the one-argument form, which only claims ownership"),
    ("addappid(123,1)", "two arguments and no key"),
    (f'-- addappid(123,1,"{KEY}")', "a commented-out line"),
    (f'addappid(123,1,"{"a" * 63}")', "63 hex characters, one short of a key"),
    (f'addappid(123,1,"{"z" * 64}")', "64 characters that are not hex"),
):
    check(found(text) == {}, why)

print("A real manifest, shaped the way the failing one was")
doc = f"""-- 4513480's Lua and Manifest Created by Hubcap Manifest
addappid(4513481,0,"{KEY}")
setManifestid(4513481,"8731916514870596703")
addappid(4513480)
"""
got = found(doc)
check(got == {"4513481": KEY},
      "the depot with a key is taken, and the bare appid is not")

print("Every manifest on this machine, if there are any")
lua_dir = pathlib.Path.home() / ".local/share/Steam/config/stplug-in"
if not lua_dir.is_dir():
    print("  skip no manifests here")
else:
    keys = sdk.collect_keys(lua_dir)
    zero = sum(1 for f in lua_dir.glob("*.lua")
               for line in f.read_text(errors="replace").splitlines()
               if line.strip().startswith("addappid(") and ",0," in line
               and line.count('"') >= 2)
    check(len(keys) > 0, f"keys are found at all ({len(keys)})")
    check(zero == 0 or len(keys) > 0,
          f"and the {zero} written with a flag of 0 are among them, not skipped")

print("\nall passed" if not failures else f"\n{failures} FAILED")
sys.exit(1 if failures else 0)
